<a href="https://colab.research.google.com/github/JADZO24/Python-data-analysis-challenges/blob/main/50DaysofDataAnalysiswithPythonDay5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

list_numbers = [[12, 23, -45], [18, -77, -44]]
arr = np.array(list_numbers)

negatives = np.where(arr < 0)
print(arr[negatives])

[-45 -77 -44]


In [2]:
arr = np.array(list_numbers)

new_arr = np.multiply(arr, 2)
new_arr

array([[  24,   46,  -90],
       [  36, -154,  -88]])

In [3]:
new_arr = np.multiply(arr, 2)

sum_axis_1 = np.sum(new_arr, axis=1)
sum_axis_1

array([ -20, -206])

In [4]:
new_arr = np.multiply(arr, 2)

sum_axis_0 = np.sum(new_arr, axis=0)
sum_axis_0

array([  60, -108, -178])

In [5]:
array1 = np.arange(100).reshape(2, 5, 10)
array1

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [9]:
selection = array1[1,0]
selection

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [10]:
list_numbers = [[12, 23, -45], [18, -77, -44]]
arr = np.array(list_numbers)

array_row_one = arr[0]
array_row_two = arr[1]
nums_greater = np.greater(array_row_one, array_row_two)
print(f"The numbers in row 1 that are greater are: {sum(nums_greater)}")

The numbers in row 1 that are greater are: 1
