<a href="https://colab.research.google.com/github/JADZO24/Python-data-analysis-challenges/blob/main/50DaysofDataAnalysiswithPythonDay2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
list1 = [2,3,4,6]

# creating an array from list
arr = np.array(list1)
arr

array([2, 3, 4, 6])

In [ ]:
# Checking the version of NumPy
np.__version__

'1.25.2'

In [ ]:
arr.shape

(4,)

In [ ]:
# Checking size
arr_size = np.size(arr)
print("The Number of Itemms in the array: ", arr_size)

The Number of Itemms in the array:  4


In [ ]:
def reverse_array(array):
    return array[::-1]

arr = np.array(list1)

arr_reversed = reverse_array(arr)
arr_reversed

array([6, 4, 3, 2])

In [ ]:
# OR
arr = np.array(list1)

# Reversing array using flip
flip_arr = np.flip(arr, axis=0)
flip_arr

array([6, 4, 3, 2])

In [ ]:
list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]

arr = np.array([list1, list2])
arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

In [ ]:
arr.shape

(2, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
list1 = [2, 3, 4, 6]
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1]

arr = np.array([list1,list2, list3], dtype='int64')
arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
lst = [1, 2.5, 3, 4.2, 5]

# Creating an array from a list of floats and integers
my_array = np.array(lst)
my_array.dtype

dtype('float64')